#!/bin/bash
#SBATCH -t 165:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --job-name=simple
#SBATCH --partition=all
#SBATCH --gres=gpu:1
#SBATCH --mem=64G
#SBATCH --cpus-per-task=16
#SBATCH --constraint="3090|A5000|titan_rtx"         # Request Specific GPUs (modify if needed)
#SBATCH --output=./outputs/slurm_output_%A.out
#SBATCH --export=ALL,WANDB_API_KEY=dfcd2574507b9ebe69ca13ab6f6925d864e82ee0

echo "TX Adaptivity Experiments"
echo | date
echo "Node name: $(hostname)"
echo -n memory=; ulimit -m
echo -n nproc=; nproc

# Initialize Conda and activate environment
eval "$(conda shell.bash hook)"
conda activate prune_llm

# Distributed Training Setup (if using DDP)
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=$((15000 + RANDOM % 5000))  # Use random port
export WORLD_SIZE=$SLURM_NTASKS
export RANK=$SLURM_PROCID
export LOCAL_RANK=$SLURM_LOCALID
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export CUDA_LAUNCH_BLOCKING=1

nvidia-smi

# srun python datasets.py
# srun python compare_tensor.py
# srun python latency.py
srun python switching.py


echo "Job Complete"
echo | date