#!/bin/bash
#SBATCH --job-name=simple
#SBATCH -t 165:00:00
#SBATCH --partition=all           # Change based on cluster
#SBATCH --nodes=1                 # Number of nodes
#SBATCH --ntasks-per-node=4       # One task per node
#SBATCH --gres=gpu:4              # GPUs per node (adjust if needed)
#SBATCH --mem=248G                # Memory per node
#SBATCH --cpus-per-task=12        # CPU cores per task
#SBATCH --constraint="3090|A5000"         # Request Specific GPUs (modify if needed)
#SBATCH --output=./outputs/slurm_output_%A.out
#SBATCH --exclude=ivi-cn005,ivi-cn009,ivi-cn010,ivi-cn011,ivi-cn012,ivi-cn001
#SBATCH --export=ALL,WANDB_API_KEY=dfcd2574507b9ebe69ca13ab6f6925d864e82ee0

echo "ViT Adaptivity 1-level 100k train samples 10k val samples"
echo | date
echo "Node name: $(hostname)"
echo -n memory=; ulimit -m
echo -n nproc=; nproc

nvidia-smi

# Initialize Conda and activate environment
eval "$(conda shell.bash hook)"
conda activate prune_llm

# Distributed Training Setup (if using DDP)
export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=$((15000 + RANDOM % 5000))  # Use random port
export WORLD_SIZE=$SLURM_NTASKS
export RANK=$SLURM_PROCID
export LOCAL_RANK=$SLURM_LOCALID

srun python ViT_adaptivity.py \
    --exp_name ViT_Adaptivity_saveDebug \
    --model_name google/vit-base-patch16-224 \
    --pruning_type l1 \
    --pruning_ratio 0.25 \
    --taylor_batchs 10 \
    --data_path /ssdstore/ImageNet/ \
    --train_batch_size 128 \
    --val_batch_size 128 \
    --save_as saves/state_dicts/ \
    --test_accuracy \
    --rebuild \
    --epochs 100 \
    --distributed --model-ema \
    --amp --ra-sampler \
    --log_wandb


# CUDA_LAUNCH_BLOCKING=1 srun python ViT_adaptivity.py \
#     --exp_name Freezing_Debug \
#     --model_name google/vit-base-patch16-224 \
#     --pruning_type l1 \
#     --pruning_ratio 0.25 \
#     --taylor_batchs 10 \
#     --data_path /ssdstore/ImageNet/ \
#     --train_batch_size 128 \
#     --val_batch_size 128 \
#     --save_as saves/state_dicts/ \
#     --test_accuracy \
#     --rebuild \
#     --epochs 2 \
#     --distributed --model-ema \
#     --amp --ra-sampler \
#     --debug \

echo "Job Complete"
echo | date